<?php declare(strict_types=1); ?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4">
    <div>
        <h1 class="h3 mb-1">Paket LPJ BUMDes</h1>
        <p class="text-secondary mb-0">Generator paket laporan pertanggungjawaban yang menggabungkan ringkasan eksekutif, laporan keuangan utama, CaLK ringkas, dan halaman pengesahan agar lebih siap dipakai untuk desa, kecamatan, maupun pembinaan kabupaten.</p>
    </div>
    <?php if (!empty($hasReport)): ?>
        <div class="d-flex gap-2 flex-wrap">
            <form method="post" action="<?= e(base_url('/lpj/print')) ?>" target="_blank" class="m-0">
                <input type="hidden" name="_token" value="<?= e(csrf_token()) ?>">
                <?php foreach (($filters ?? []) as $key => $value): ?><input type="hidden" name="<?= e((string) $key) ?>" value="<?= e((string) $value) ?>"><?php endforeach; ?>
                <?php foreach (($signatoryInput ?? []) as $key => $value): ?><input type="hidden" name="<?= e((string) $key) ?>" value="<?= e((string) $value) ?>"><?php endforeach; ?>
                <button type="submit" class="btn btn-outline-light">Cetak Paket</button>
            </form>
            <form method="post" action="<?= e(base_url('/lpj/pdf')) ?>" target="_blank" class="m-0">
                <input type="hidden" name="_token" value="<?= e(csrf_token()) ?>">
                <?php foreach (($filters ?? []) as $key => $value): ?><input type="hidden" name="<?= e((string) $key) ?>" value="<?= e((string) $value) ?>"><?php endforeach; ?>
                <?php foreach (($signatoryInput ?? []) as $key => $value): ?><input type="hidden" name="<?= e((string) $key) ?>" value="<?= e((string) $value) ?>"><?php endforeach; ?>
                <button type="submit" class="btn btn-primary">Export PDF</button>
            </form>
        </div>
    <?php endif; ?>
</div>

<div class="card shadow-sm mb-4"><div class="card-body p-4">
    <form method="post" action="<?= e(base_url('/lpj')) ?>" class="row g-3 align-items-start">
        <input type="hidden" name="_token" value="<?= e(csrf_token()) ?>">
        <div class="col-lg-4"><label for="period_id" class="form-label">Filter Periode</label><select name="period_id" id="period_id" class="form-select"><option value="">Semua periode / manual tanggal</option><?php foreach ($periods as $period): ?><option value="<?= e((string) $period['id']) ?>" <?= (string) ($filters['period_id'] ?? '') === (string) $period['id'] ? 'selected' : '' ?>><?= e($period['period_name'] . ' (' . $period['period_code'] . ')') ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-2"><label for="fiscal_year" class="form-label">Tahun</label><select name="fiscal_year" id="fiscal_year" class="form-select"><option value="">Semua tahun</option><?php foreach (($reportYears ?? []) as $year): ?><option value="<?= e((string) $year) ?>" <?= (string) ($filters['fiscal_year'] ?? '') === (string) $year ? 'selected' : '' ?>><?= e((string) $year) ?></option><?php endforeach; ?></select></div><div class="col-lg-3"><label for="unit_id" class="form-label">Unit Usaha</label><select name="unit_id" id="unit_id" class="form-select"><option value="">Semua Unit</option><?php foreach ($units as $unit): ?><option value="<?= e((string) $unit['id']) ?>" <?= (string) ($filters['unit_id'] ?? '') === (string) $unit['id'] ? 'selected' : '' ?>><?= e($unit['unit_code'] . ' - ' . $unit['unit_name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-2"><label for="date_from" class="form-label">Tanggal Mulai</label><input type="date" name="date_from" id="date_from" class="form-control" value="<?= e((string) ($filters['date_from'] ?? '')) ?>"></div>
        <div class="col-lg-2"><label for="date_to" class="form-label">Tanggal Akhir</label><input type="date" name="date_to" id="date_to" class="form-control" value="<?= e((string) ($filters['date_to'] ?? '')) ?>"></div>
        <div class="col-lg-1"><label for="package_type" class="form-label">Jenis</label><select name="package_type" id="package_type" class="form-select"><?php foreach (lpj_package_type_options() as $value => $label): ?><option value="<?= e($value) ?>" <?= (string) ($filters['package_type'] ?? 'auto') === (string) $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div>

        <div class="col-lg-4"><label for="document_no" class="form-label">Nomor Dokumen LPJ</label><input type="text" name="document_no" id="document_no" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['document_no'] ?? '')) ?>" placeholder="Contoh: 01/LPJ/BUMDES/2026"></div>
        <div class="col-lg-3"><label for="approval_date" class="form-label">Tanggal Pengesahan</label><input type="date" name="approval_date" id="approval_date" class="form-control" value="<?= e((string) ($signatoryInput['approval_date'] ?? date('Y-m-d'))) ?>"></div>
        <div class="col-lg-3"><label for="advisor_name" class="form-label">Nama Penasihat / Kepala Desa</label><input type="text" name="advisor_name" id="advisor_name" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['advisor_name'] ?? '')) ?>" placeholder="Opsional tetapi disarankan diisi"></div>
        <div class="col-lg-2"><label for="advisor_position" class="form-label">Jabatan Penasihat</label><input type="text" name="advisor_position" id="advisor_position" maxlength="80" class="form-control" value="<?= e((string) ($signatoryInput['advisor_position'] ?? 'Penasihat')) ?>"></div>
        <div class="col-lg-3"><label for="supervisor_name" class="form-label">Nama Pengawas</label><input type="text" name="supervisor_name" id="supervisor_name" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['supervisor_name'] ?? '')) ?>" placeholder="Opsional tetapi disarankan diisi"></div>
        <div class="col-lg-3"><label for="supervisor_position" class="form-label">Jabatan Pengawas</label><input type="text" name="supervisor_position" id="supervisor_position" maxlength="80" class="form-control" value="<?= e((string) ($signatoryInput['supervisor_position'] ?? 'Pengawas')) ?>"></div>
        <div class="col-lg-6"><label for="approval_basis" class="form-label">Dasar Pengesahan / Catatan Formal</label><input type="text" name="approval_basis" id="approval_basis" maxlength="255" class="form-control" value="<?= e((string) ($signatoryInput['approval_basis'] ?? '')) ?>" placeholder="Contoh: Dibahas dalam rapat pengelola dan pemeriksaan internal BUMDes"></div>
        <div class="col-lg-6"><label for="meeting_reference" class="form-label">Nomor Berita Acara / Referensi Rapat</label><input type="text" name="meeting_reference" id="meeting_reference" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['meeting_reference'] ?? '')) ?>" placeholder="Opsional"></div>
        <div class="col-lg-4"><label for="recipient_name" class="form-label">Nama Penerima Dokumen</label><input type="text" name="recipient_name" id="recipient_name" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['recipient_name'] ?? '')) ?>" placeholder="Contoh: Camat / Kepala Desa"></div>
        <div class="col-lg-4"><label for="recipient_position" class="form-label">Jabatan Penerima</label><input type="text" name="recipient_position" id="recipient_position" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['recipient_position'] ?? '')) ?>" placeholder="Contoh: Camat / Kepala Desa"></div>
        <div class="col-lg-4"><label for="recipient_institution" class="form-label">Instansi / Tujuan Dokumen</label><input type="text" name="recipient_institution" id="recipient_institution" maxlength="120" class="form-control" value="<?= e((string) ($signatoryInput['recipient_institution'] ?? '')) ?>" placeholder="Contoh: Pemerintah Desa / Kecamatan"></div>
        <div class="col-12"><label for="appendix_summary" class="form-label">Ringkasan Lampiran Bundel</label><textarea name="appendix_summary" id="appendix_summary" rows="2" class="form-control" placeholder="Opsional. Isi jika ingin menuliskan ringkasan lampiran secara spesifik."><?= e((string) ($signatoryInput['appendix_summary'] ?? '')) ?></textarea></div>
        <div class="col-lg-6"><label for="executive_summary" class="form-label">Ringkasan Eksekutif</label><textarea name="executive_summary" id="executive_summary" rows="3" class="form-control" placeholder="Bisa dibiarkan kosong agar sistem mengisi otomatis."><?= e((string) ($narratives['executive_summary'] ?? '')) ?></textarea></div>
        <div class="col-lg-6"><label for="business_overview" class="form-label">Keadaan dan Jalannya BUMDes</label><textarea name="business_overview" id="business_overview" rows="3" class="form-control" placeholder="Uraikan kondisi operasional dan tata kelola periode laporan."><?= e((string) ($narratives['business_overview'] ?? '')) ?></textarea></div>
        <div class="col-lg-6"><label for="activities_summary" class="form-label">Kegiatan Utama</label><textarea name="activities_summary" id="activities_summary" rows="3" class="form-control" placeholder="Rangkum kegiatan dan capaian utama."><?= e((string) ($narratives['activities_summary'] ?? '')) ?></textarea></div>
        <div class="col-lg-6"><label for="problems_summary" class="form-label">Masalah / Catatan Penting</label><textarea name="problems_summary" id="problems_summary" rows="3" class="form-control" placeholder="Jelaskan kendala, temuan, atau hal yang perlu perhatian."><?= e((string) ($narratives['problems_summary'] ?? '')) ?></textarea></div>
        <div class="col-12"><label for="follow_up_summary" class="form-label">Tindak Lanjut / Rencana Perbaikan</label><textarea name="follow_up_summary" id="follow_up_summary" rows="3" class="form-control" placeholder="Isi rencana perbaikan setelah LPJ dibahas."><?= e((string) ($narratives['follow_up_summary'] ?? '')) ?></textarea></div>
        <div class="col-12 d-flex gap-2 flex-wrap"><button type="submit" class="btn btn-primary">Tampilkan Paket</button><?php if (!empty($hasReport)): ?><button type="submit" formaction="<?= e(base_url('/lpj/print')) ?>" formtarget="_blank" class="btn btn-outline-light">Cetak Paket</button><button type="submit" formaction="<?= e(base_url('/lpj/pdf')) ?>" formtarget="_blank" class="btn btn-success">Export PDF</button><?php endif; ?></div>
    </form>
</div></div>

<?php if (empty($hasReport)): ?>
    <div class="card shadow-sm"><div class="card-body p-5 text-center text-secondary">Pilih periode atau isi tanggal filter, lalu klik <strong class="text-light">Tampilkan Paket</strong> untuk menyusun LPJ BUMDes yang siap dicetak.</div></div>
<?php else: ?>
    <div class="row g-4 mb-4">
        <div class="col-md-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Jenis Paket</div><div class="fw-semibold"><?= e($packageLabel) ?></div><div class="text-secondary small"><?= e(report_period_label($filters, $selectedPeriod)) ?></div></div></div></div>
        <div class="col-md-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Unit Usaha</div><div class="fw-semibold"><?= e($selectedUnitLabel) ?></div><div class="text-secondary small">Lingkup pertanggungjawaban</div></div></div></div>
        <div class="col-md-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Status Neraca</div><div class="fw-semibold <?= !empty($balanceSheet['is_balanced']) ? 'text-success' : 'text-danger' ?>"><?= !empty($balanceSheet['is_balanced']) ? 'Seimbang' : 'Perlu Cek' ?></div><div class="text-secondary small">Selisih <?= e(ledger_currency(abs((float) ($balanceSheet['difference'] ?? 0)))) ?></div></div></div></div>
        <div class="col-md-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Nomor Dokumen</div><div class="fw-semibold"><?= e((string) (($signatoryInput['document_no'] ?? '') !== '' ? $signatoryInput['document_no'] : '-')) ?></div><div class="text-secondary small"><?= e(lpj_approval_city_date($profile, (string) ($signatoryInput['approval_date'] ?? date('Y-m-d')))) ?></div></div></div></div>
    </div>

    <div class="row g-4 mb-4">
        <?php foreach (lpj_summary_cards($summary) as $card): ?><div class="col-md-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1"><?= e((string) $card['label']) ?></div><div class="fw-semibold mb-1"><?= e((string) $card['value']) ?></div><div class="small text-secondary"><?= e((string) $card['note']) ?></div></div></div></div><?php endforeach; ?>
    </div>

    <div class="row g-4 mb-4">
        <div class="col-lg-5"><div class="card shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Isi Paket LPJ</h2><div class="d-flex flex-column gap-3"><?php foreach ($sections as $index => $section): ?><div class="d-flex gap-3 align-items-start"><div class="badge rounded-pill text-bg-primary mt-1"><?= e((string) ($index + 1)) ?></div><div><div class="fw-semibold"><?= e((string) $section['title']) ?></div><div class="small text-secondary"><?= e((string) $section['note']) ?></div></div></div><?php endforeach; ?></div></div></div></div>
        <div class="col-lg-7"><div class="card shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Ringkasan Narasi</h2><div class="small text-secondary mb-2">Ringkasan Eksekutif</div><p class="mb-3"><?= e(lpj_shorten((string) ($narratives['executive_summary'] ?? ''), 260)) ?></p><div class="small text-secondary mb-2">Keadaan BUMDes</div><p class="mb-3"><?= e(lpj_shorten((string) ($narratives['business_overview'] ?? ''), 220)) ?></p><div class="small text-secondary mb-2">Masalah dan Tindak Lanjut</div><p class="mb-0"><?= e(lpj_shorten((string) ($narratives['problems_summary'] ?? ''), 220)) ?></p></div></div></div>
    </div>

    <?php if ($issues !== []): ?><div class="alert alert-warning mb-4"><div class="fw-semibold mb-2">Sorotan Perhatian</div><ul class="mb-0 ps-3"><?php foreach ($issues as $issue): ?><li><?= e((string) $issue) ?></li><?php endforeach; ?></ul></div><?php endif; ?>

    <div class="row g-4 mb-4">
        <div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Pratinjau Laba Rugi</h2><div class="table-responsive"><table class="table table-dark table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Akun</th><th class="text-end">Nilai</th></tr></thead><tbody><tr class="table-secondary"><td colspan="3" class="fw-semibold">Pendapatan</td></tr><?php if ($profitLoss['revenue_rows'] === []): ?><tr><td colspan="3" class="text-center text-secondary py-4">Tidak ada akun pendapatan.</td></tr><?php else: foreach ($profitLoss['revenue_rows'] as $row): ?><tr><td><?= e((string) $row['account_code']) ?></td><td><?= e((string) $row['account_name']) ?></td><td class="text-end"><?= e(ledger_currency((float) $row['amount'])) ?></td></tr><?php endforeach; endif; ?><tr class="table-secondary"><td colspan="2" class="text-end fw-semibold">Total Pendapatan</td><td class="text-end fw-bold"><?= e(ledger_currency((float) $profitLoss['total_revenue'])) ?></td></tr><tr class="table-secondary"><td colspan="3" class="fw-semibold">Beban</td></tr><?php if ($profitLoss['expense_rows'] === []): ?><tr><td colspan="3" class="text-center text-secondary py-4">Tidak ada akun beban.</td></tr><?php else: foreach ($profitLoss['expense_rows'] as $row): ?><tr><td><?= e((string) $row['account_code']) ?></td><td><?= e((string) $row['account_name']) ?></td><td class="text-end"><?= e(ledger_currency((float) $row['amount'])) ?></td></tr><?php endforeach; endif; ?><tr class="table-secondary"><td colspan="2" class="text-end fw-semibold"><?= e(profit_loss_result_label((float) $profitLoss['net_income'])) ?></td><td class="text-end fw-bold"><?= e(ledger_currency((float) $profitLoss['net_income'])) ?></td></tr></tbody></table></div></div></div></div>
        <div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Pratinjau Posisi Keuangan</h2><div class="table-responsive"><table class="table table-dark table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Akun</th><th class="text-end">Saldo Akhir</th><?php if (!empty($balanceSheet['comparison_enabled'])): ?><th class="text-end">Pembanding</th><?php endif; ?></tr></thead><tbody><tr class="table-secondary"><td colspan="<?= !empty($balanceSheet['comparison_enabled']) ? '4' : '3' ?>" class="fw-semibold">Aset</td></tr><?php foreach ($balanceSheet['asset_rows'] as $row): ?><tr><td><?= e((string) $row['account_code']) ?></td><td><?= e((string) $row['account_name']) ?></td><td class="text-end"><?= e(ledger_currency((float) $row['amount'])) ?></td><?php if (!empty($balanceSheet['comparison_enabled'])): ?><td class="text-end text-secondary"><?= e(ledger_currency((float) ($row['comparison_amount'] ?? 0))) ?></td><?php endif; ?></tr><?php endforeach; ?><tr class="table-secondary"><td colspan="2" class="text-end fw-semibold">Total Aset</td><td class="text-end fw-bold"><?= e(ledger_currency((float) $balanceSheet['total_assets'])) ?></td><?php if (!empty($balanceSheet['comparison_enabled'])): ?><td class="text-end fw-bold"><?= e(ledger_currency((float) ($balanceSheet['comparison_total_assets'] ?? 0))) ?></td><?php endif; ?></tr></tbody></table></div></div></div></div>
    </div>

    <div class="row g-4 mb-4">
        <div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Pratinjau Arus Kas</h2><div class="table-responsive"><table class="table table-dark table-hover align-middle mb-0"><thead><tr><th>Komponen</th><th class="text-end">Nilai</th></tr></thead><tbody><tr><td>Kas Awal</td><td class="text-end"><?= e(ledger_currency((float) $cashFlow['opening_cash'])) ?></td></tr><tr><td>Arus Kas Bersih Operasional</td><td class="text-end"><?= e(ledger_currency((float) $cashFlow['total_operating'])) ?></td></tr><tr><td>Arus Kas Bersih Investasi</td><td class="text-end"><?= e(ledger_currency((float) $cashFlow['total_investing'])) ?></td></tr><tr><td>Arus Kas Bersih Pendanaan</td><td class="text-end"><?= e(ledger_currency((float) $cashFlow['total_financing'])) ?></td></tr><tr class="table-secondary"><td class="fw-semibold">Kas Akhir</td><td class="text-end fw-bold"><?= e(ledger_currency((float) $cashFlow['closing_cash'])) ?></td></tr></tbody></table></div></div></div></div>
        <div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 mb-3">Pratinjau Perubahan Ekuitas</h2><div class="table-responsive"><table class="table table-dark table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Akun</th><th class="text-end">Saldo Akhir</th></tr></thead><tbody><?php if ($equityChanges['rows'] === []): ?><tr><td colspan="3" class="text-center text-secondary py-4">Tidak ada data ekuitas.</td></tr><?php else: foreach ($equityChanges['rows'] as $row): ?><tr><td><?= e((string) $row['account_code']) ?></td><td><?= e((string) $row['account_name']) ?></td><td class="text-end"><?= e(ledger_currency((float) $row['closing_amount'])) ?></td></tr><?php endforeach; endif; ?><tr class="table-secondary"><td colspan="2" class="text-end fw-semibold">Total Ekuitas Akhir</td><td class="text-end fw-bold"><?= e(ledger_currency((float) $equityChanges['final_equity_total'])) ?></td></tr></tbody></table></div></div></div></div>
    </div>

    <div class="card shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Pratinjau CaLK Ringkas</h2><div class="row g-4"><?php foreach ($financialNotes as $section): ?><div class="col-lg-6"><div class="border rounded-4 p-3 h-100"><div class="fw-semibold mb-2"><?= e((string) ($section['title'] ?? '')) ?></div><?php foreach (array_slice((array) ($section['paragraphs'] ?? []), 0, 2) as $paragraph): ?><p class="small text-secondary mb-2"><?= e((string) $paragraph) ?></p><?php endforeach; ?><?php $rows = lpj_visible_note_rows((array) ($section['rows'] ?? []), 3); if ($rows !== []): ?><div class="small text-secondary mb-2">Akun penting</div><ul class="small mb-0 ps-3"><?php foreach ($rows as $row): ?><li><?= e((string) ($row['account_name'] ?? '-')) ?> — <?= e(financial_notes_currency((float) ($row['amount'] ?? 0))) ?></li><?php endforeach; ?></ul><?php endif; ?></div></div><?php endforeach; ?></div></div></div>
<?php endif; ?>
