<?php declare(strict_types=1); ?>
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4">
    <div>
        <h1 class="h3 mb-1">Neraca Saldo</h1>
        <p class="text-secondary mb-0">Ringkasan saldo seluruh akun aktif yang relevan, dengan dukungan filter unit usaha.</p>
    </div>
    <?php if ($filters['date_to'] !== ''): ?>
        <div class="d-flex gap-2">
            <a href="<?= e(base_url('/trial-balance/print?' . report_filters_query($filters))) ?>" target="_blank" class="btn btn-outline-light">Print</a>
            <a href="<?= e(base_url('/trial-balance/pdf?' . report_filters_query($filters))) ?>" target="_blank" class="btn btn-primary">Export PDF</a>
        </div>
    <?php endif; ?>
</div>
<div class="card shadow-sm mb-4"><div class="card-body p-4"><form method="get" action="<?= e(base_url('/trial-balance')) ?>" class="row g-3 align-items-end"><div class="col-lg-3"><label class="form-label">Periode</label><select name="period_id" class="form-select"><option value="">Semua periode / manual tanggal</option><?php foreach ($periods as $period): ?><option value="<?= e((string) $period['id']) ?>" <?= (string) $filters['period_id'] === (string) $period['id'] ? 'selected' : '' ?>><?= e($period['period_name'] . ' (' . $period['period_code'] . ')') ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label">Tahun</label><select name="fiscal_year" class="form-select"><option value="">Semua tahun</option><?php foreach (($reportYears ?? []) as $year): ?><option value="<?= e((string) $year) ?>" <?= (string) ($filters['fiscal_year'] ?? '') === (string) $year ? 'selected' : '' ?>><?= e((string) $year) ?></option><?php endforeach; ?></select></div><div class="col-lg-3"><label class="form-label">Unit Usaha</label><select name="unit_id" class="form-select"><option value="">Semua Unit</option><?php foreach (($units ?? []) as $unit): ?><option value="<?= e((string) $unit['id']) ?>" <?= (string) $filters['unit_id'] === (string) $unit['id'] ? 'selected' : '' ?>><?= e($unit['unit_code'] . ' - ' . $unit['unit_name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label">Mulai</label><input type="date" name="date_from" class="form-control" value="<?= e((string) $filters['date_from']) ?>"></div><div class="col-lg-2"><label class="form-label">Akhir</label><input type="date" name="date_to" class="form-control" value="<?= e((string) $filters['date_to']) ?>"></div><div class="col-lg-2 d-grid"><button type="submit" class="btn btn-primary">Tampil</button></div></form></div></div>
<?php if ($filters['date_to'] !== ''): ?>
<div class="row g-4 mb-4">
    <div class="col-md-6 col-xl-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Rentang Data</div><div class="fw-semibold"><?= e(format_id_date((string) $filters['date_from'])) ?> s.d. <?= e(format_id_date((string) $filters['date_to'])) ?></div><div class="text-secondary small"><?= e($selectedPeriod['period_name'] ?? 'Filter tanggal manual') ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Unit Usaha</div><div class="fw-semibold"><?= e(business_unit_label($selectedUnit)) ?></div><div class="text-secondary small">Ruang lingkup laporan</div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Jumlah Akun</div><div class="fs-5 fw-semibold"><?= e((string) $summary['account_count']) ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Total Debit / Kredit</div><div class="fw-semibold">D <?= e(ledger_currency((float) $summary['total_debit'])) ?></div><div class="fw-semibold">K <?= e(ledger_currency((float) $summary['total_credit'])) ?></div></div></div></div>
</div>
<div class="card shadow-sm"><div class="card-body p-0"><div class="table-responsive trial-balance-table-wrapper"><table class="table table-dark table-hover align-middle mb-0 coa-table trial-balance-table"><thead><tr><th>Kode Akun</th><th>Nama Akun</th><th>Tipe</th><th class="text-end">Debit</th><th class="text-end">Kredit</th><th class="text-end">Saldo Akhir</th></tr></thead><tbody><?php if ($rows === []): ?><tr><td colspan="6" class="text-center text-secondary py-5">Tidak ada data neraca saldo untuk filter yang dipilih.</td></tr><?php else: foreach ($rows as $row): ?><tr><td class="fw-semibold"><?= e((string) $row['account_code']) ?></td><td><?= e((string) $row['account_name']) ?></td><td><span class="badge text-bg-secondary"><?= e((string) $row['account_type']) ?></span></td><td class="text-end fw-semibold"><?= e(ledger_currency((float) $row['period_debit'])) ?></td><td class="text-end fw-semibold"><?= e(ledger_currency((float) $row['period_credit'])) ?></td><td class="text-end fw-semibold"><?= e(ledger_currency((float) $row['closing_balance'])) ?><?php if ((string) $row['closing_side'] !== '-'): ?><span class="badge rounded-pill text-bg-info ms-1"><?= e((string) $row['closing_side']) ?></span><?php endif; ?></td></tr><?php endforeach; endif; ?></tbody><tfoot><tr><th colspan="3" class="text-end">Total</th><th class="text-end"><?= e(ledger_currency((float) $summary['total_debit'])) ?></th><th class="text-end"><?= e(ledger_currency((float) $summary['total_credit'])) ?></th><th class="text-end"><div>D <?= e(ledger_currency((float) $summary['ending_debit_total'])) ?></div><div>K <?= e(ledger_currency((float) $summary['ending_credit_total'])) ?></div></th></tr></tfoot></table></div></div></div>
<?php else: ?><div class="card shadow-sm"><div class="card-body p-5 text-center text-secondary">Pilih periode atau isi tanggal filter, lalu klik <strong class="text-light">Tampil</strong> untuk melihat neraca saldo.</div></div><?php endif; ?>
