<?php declare(strict_types=1); ?>
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4">
    <div>
        <h1 class="h3 mb-1">Laporan Perubahan Ekuitas</h1>
        <p class="text-secondary mb-0">Mutasi ekuitas untuk periode laporan, dengan saldo awal, mutasi periode, dan saldo akhir yang lebih mudah dibaca.</p>
    </div>
    <?php if ($filters['date_to'] !== ''): ?>
        <div class="d-flex gap-2">
            <a href="<?= e(base_url('/equity-changes/print?' . report_filters_query($filters))) ?>" target="_blank" class="btn btn-outline-light">Print</a>
            <a href="<?= e(base_url('/equity-changes/pdf?' . report_filters_query($filters))) ?>" target="_blank" class="btn btn-primary">Export PDF</a>
        </div>
    <?php endif; ?>
</div>
<div class="card shadow-sm mb-4"><div class="card-body p-4"><form method="get" action="<?= e(base_url('/equity-changes')) ?>" class="row g-3 align-items-end"><input type="hidden" name="filter_scope" value="<?= e(report_filter_scope($filters)) ?>"><div class="col-lg-2"><label for="period_id" class="form-label">Periode Awal</label><select name="period_id" id="period_id" class="form-select"><?= report_period_select_options($periods, (int) ($filters['period_id'] ?? 0), 'Manual tanggal') ?></select></div><div class="col-lg-2"><label for="period_to_id" class="form-label">Sampai Periode</label><select name="period_to_id" id="period_to_id" class="form-select"><?= report_period_select_options($periods, (int) ($filters['period_to_id'] ?? 0), 'Sama dengan periode awal') ?></select></div><div class="col-lg-2"><label for="fiscal_year" class="form-label">Tahun</label><select name="fiscal_year" id="fiscal_year" class="form-select"><option value="">Semua tahun</option><?php foreach (($reportYears ?? []) as $year): ?><option value="<?= e((string) $year) ?>" <?= (string) ($filters['fiscal_year'] ?? '') === (string) $year ? 'selected' : '' ?>><?= e((string) $year) ?></option><?php endforeach; ?></select></div><div class="col-lg-3"><label for="unit_id" class="form-label">Unit Usaha</label><select name="unit_id" id="unit_id" class="form-select"><option value="">Semua Unit</option><?php foreach ($units as $unit): ?><option value="<?= e((string) $unit['id']) ?>" <?= (string) $filters['unit_id'] === (string) $unit['id'] ? 'selected' : '' ?>><?= e($unit['unit_code'] . ' - ' . $unit['unit_name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label for="date_from" class="form-label">Tanggal Awal</label><input type="date" name="date_from" id="date_from" class="form-control" value="<?= e((string) $filters['date_from']) ?>"></div><div class="col-lg-2"><label for="date_to" class="form-label">Tanggal Akhir Laporan</label><input type="date" name="date_to" id="date_to" class="form-control" value="<?= e((string) $filters['date_to']) ?>"></div><div class="col-lg-1 d-grid"><button type="submit" class="btn btn-primary">Tampil</button></div></form></div></div>
<?php if ($filters['date_to'] !== ''): ?>
<div class="row g-4 mb-4"><div class="col-md-4"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Periode</div><div class="fw-semibold"><?= e(report_period_label($filters, $selectedPeriod)) ?></div><div class="text-secondary small"><?= e($selectedPeriod['period_name'] ?? 'Tanggal bebas') ?></div></div></div></div><div class="col-md-4"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Unit Usaha</div><div class="fw-semibold"><?= e($selectedUnitLabel) ?></div><div class="text-secondary small">Ruang lingkup laporan</div></div></div></div><div class="col-md-4"><div class="card dashboard-card h-100"><div class="card-body p-4"><div class="text-secondary small mb-1">Ekuitas Akhir</div><div class="fw-semibold"><?= e(ledger_currency((float) $report['final_equity_total'])) ?></div><div class="text-secondary small">Setelah laba/rugi berjalan</div></div></div></div></div>
<div class="card shadow-sm"><div class="card-body p-0"><div class="table-responsive coa-table-wrapper"><table class="table table-dark table-hover align-middle mb-0 coa-table"><thead><tr><th>Kode</th><th>Nama Akun</th><th class="text-end">Saldo Awal</th><th class="text-end">Mutasi</th><th class="text-end">Saldo Akhir</th></tr></thead><tbody><?php if ($report['rows'] === []): ?><tr><td colspan="5" class="text-center text-secondary py-4">Tidak ada data ekuitas untuk filter yang dipilih.</td></tr><?php else: foreach ($report['rows'] as $row): ?><tr><td class="fw-semibold"><?= e((string) $row['account_code']) ?></td><td><?= e((string) $row['account_name']) ?></td><td class="text-end"><?= e(ledger_currency((float) $row['opening_amount'])) ?></td><td class="text-end"><?= e(ledger_currency((float) $row['movement_amount'])) ?></td><td class="text-end fw-semibold"><?= e(ledger_currency((float) $row['closing_amount'])) ?></td></tr><?php endforeach; endif; ?></tbody><tfoot><tr><th colspan="2" class="text-end">Total Ekuitas Langsung</th><th class="text-end"><?= e(ledger_currency((float) $report['total_opening_equity'])) ?></th><th class="text-end"><?= e(ledger_currency((float) $report['total_movement_equity'])) ?></th><th class="text-end"><?= e(ledger_currency((float) $report['total_closing_equity'])) ?></th></tr><tr><th colspan="4" class="text-end">Laba / Rugi Berjalan</th><th class="text-end"><?= e(ledger_currency((float) $report['net_income'])) ?></th></tr><tr><th colspan="4" class="text-end"><?= e(equity_change_result_label((float) $report['net_income'])) ?> / Total Ekuitas Akhir</th><th class="text-end"><?= e(ledger_currency((float) $report['final_equity_total'])) ?></th></tr></tfoot></table></div></div></div>
<?php else: ?><div class="card shadow-sm"><div class="card-body p-5 text-center text-secondary">Pilih periode atau isi tanggal filter, lalu klik <strong class="text-light">Tampil</strong> untuk melihat laporan perubahan ekuitas.</div></div><?php endif; ?>
