<?php declare(strict_types=1); ?>
<?php $action = $row ? base_url('/assets/categories/update?id=' . (int) $row['id']) : base_url('/assets/categories/store'); ?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4">
    <div>
        <h1 class="h3 mb-1"><?= e($title ?? 'Form Kategori Aset') ?></h1>
        <p class="text-secondary mb-0">Gunakan kategori universal seperti Perangkat Teknologi, Peralatan Jaringan, Peralatan Peternakan, dan Aset Biologis.</p>
    </div>
    <a href="<?= e(base_url('/assets/categories')) ?>" class="btn btn-outline-light">Kembali</a>
</div>

<div class="card shadow-sm"><div class="card-body p-4 p-lg-5">
    <form method="post" action="<?= e($action) ?>" class="row g-4">
        <input type="hidden" name="_token" value="<?= e(csrf_token()) ?>">
        <div class="col-lg-4"><label class="form-label">Kode Kategori</label><input type="text" class="form-control" name="category_code" value="<?= e((string) $formData['category_code']) ?>" maxlength="30" required></div>
        <div class="col-lg-8"><label class="form-label">Nama Kategori</label><input type="text" class="form-control" name="category_name" value="<?= e((string) $formData['category_name']) ?>" maxlength="120" required></div>
        <div class="col-lg-4"><label class="form-label">Kelompok</label><select class="form-select" name="asset_group"><?php foreach (($groups ?? []) as $code => $label): ?><option value="<?= e($code) ?>" <?= (string) $formData['asset_group'] === $code ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-4"><label class="form-label">Umur Manfaat Default (bulan)</label><input type="number" min="0" class="form-control" name="default_useful_life_months" value="<?= e((string) $formData['default_useful_life_months']) ?>"></div>
        <div class="col-lg-4"><label class="form-label">Metode Default</label><select class="form-select" name="default_depreciation_method"><?php foreach (($methods ?? []) as $code => $label): ?><option value="<?= e($code) ?>" <?= (string) $formData['default_depreciation_method'] === $code ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-4"><label class="form-label">Boleh Disusutkan?</label><select class="form-select" name="depreciation_allowed"><option value="1" <?= (string) $formData['depreciation_allowed'] === '1' ? 'selected' : '' ?>>Ya</option><option value="0" <?= (string) $formData['depreciation_allowed'] === '0' ? 'selected' : '' ?>>Tidak</option></select></div>
        <div class="col-lg-4"><label class="form-label">Status Aktif</label><select class="form-select" name="is_active"><option value="1" <?= (string) $formData['is_active'] === '1' ? 'selected' : '' ?>>Aktif</option><option value="0" <?= (string) $formData['is_active'] === '0' ? 'selected' : '' ?>>Nonaktif</option></select></div>
        <div class="col-lg-6"><label class="form-label">Akun Aset</label><select class="form-select" name="asset_coa_id"><option value="">Pilih akun aset</option><?php foreach (($coaOptions ?? []) as $coa): ?><option value="<?= e((string) $coa['id']) ?>" <?= (string) $formData['asset_coa_id'] === (string) $coa['id'] ? 'selected' : '' ?>><?= e($coa['account_code'] . ' - ' . $coa['account_name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-6"><label class="form-label">Akun Akumulasi Penyusutan</label><select class="form-select" name="accumulated_depreciation_coa_id"><option value="">Pilih akun akumulasi penyusutan</option><?php foreach (($coaOptions ?? []) as $coa): ?><option value="<?= e((string) $coa['id']) ?>" <?= (string) $formData['accumulated_depreciation_coa_id'] === (string) $coa['id'] ? 'selected' : '' ?>><?= e($coa['account_code'] . ' - ' . $coa['account_name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-6"><label class="form-label">Akun Beban Penyusutan</label><select class="form-select" name="depreciation_expense_coa_id"><option value="">Pilih akun beban penyusutan</option><?php foreach (($coaOptions ?? []) as $coa): ?><option value="<?= e((string) $coa['id']) ?>" <?= (string) $formData['depreciation_expense_coa_id'] === (string) $coa['id'] ? 'selected' : '' ?>><?= e($coa['account_code'] . ' - ' . $coa['account_name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-6"><label class="form-label">Akun Laba Pelepasan</label><select class="form-select" name="disposal_gain_coa_id"><option value="">Pilih akun laba pelepasan</option><?php foreach (($coaOptions ?? []) as $coa): ?><option value="<?= e((string) $coa['id']) ?>" <?= (string) $formData['disposal_gain_coa_id'] === (string) $coa['id'] ? 'selected' : '' ?>><?= e($coa['account_code'] . ' - ' . $coa['account_name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-6"><label class="form-label">Akun Rugi Pelepasan</label><select class="form-select" name="disposal_loss_coa_id"><option value="">Pilih akun rugi pelepasan</option><?php foreach (($coaOptions ?? []) as $coa): ?><option value="<?= e((string) $coa['id']) ?>" <?= (string) $formData['disposal_loss_coa_id'] === (string) $coa['id'] ? 'selected' : '' ?>><?= e($coa['account_code'] . ' - ' . $coa['account_name']) ?></option><?php endforeach; ?></select></div>
        <div class="col-12"><label class="form-label">Deskripsi</label><textarea class="form-control" rows="4" name="description" maxlength="1000" placeholder="Contoh: Peralatan Jaringan untuk router, switch, ODP, kabel FO; Peralatan Peternakan untuk timbangan, alat pakan, mesin pencacah."><?= e((string) $formData['description']) ?></textarea></div>
        <div class="col-12 d-flex justify-content-end gap-2 pt-2 border-top border-secondary-subtle"><a href="<?= e(base_url('/assets/categories')) ?>" class="btn btn-outline-light">Batal</a><button type="submit" class="btn btn-primary">Simpan Kategori</button></div>
    </form>
</div></div>
